//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokrageWebApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int PolicyId { get; set; }
        public Nullable<int> CustommerId { get; set; }
        public Nullable<int> InsurerId { get; set; }
        public Nullable<int> PolicyTypeId { get; set; }
        public Nullable<double> Premium { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Insurer Insurer { get; set; }
        public virtual PolicyType PolicyType { get; set; }
        public virtual Status Status { get; set; }
    }
}
